@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjozLCJleHAiOjE2NDg1MzI3Nzd9.nHNXLbUCOtpx8RRA8DrWgFcNWHRjzsXGJokP2DHAE3k
### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "hiro",
  "email": "hiro@test.com",
  "password": "password",
  "password_confirmation": "password"
}
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "hiro@test.com",
  "password": "password"
}
### Dog create
POST http://localhost:3000/dogs.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Jack",
  "age": 1,
  "breed": "Terrier"
}