@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoyLCJleHAiOjE2NDg1MzE4MDN9.Ou5azRUabxdThBTDfrWDnbSuUE6qE0vRoi4NaUsB-7E
### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "bob",
  "email": "bob@test.com",
  "password": "password",
  "password_confirmation": "password"
}
### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "bob@test.com",
  "password": "password"
}
### Dog create
POST http://localhost:3000/dogs.json
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
  "name": "Jack",
  "age": 1,
  "breed": "Terrier"
}